# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: iOS Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4-beta' # Use Xcode 15.4 beta
    
    - name: Build iOS App
      run: |
        xcodebuild clean build \
          -project Decaff.xcodeproj \
          -scheme Decaff \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.4' \
          CODE_SIGNING_ALLOWED=NO

    - name: Run Tests
      run: |
        xcodebuild test \
          -project Decaff.xcodeproj \
          -scheme Decaff \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.4' \
          CODE_SIGNING_ALLOWED=NO
