# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
      
    - name: Build iOS App
      run: |
        xcodebuild clean build \
          -project Decaff.xcodeproj \
          -scheme Decaff \
          -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest' \
          CODE_SIGNING_ALLOWED=NO

    - name: Run Tests
      run: |
        xcodebuild test \
          -project Decaff.xcodeproj \
          -scheme Decaff \
          -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=latest' \
          CODE_SIGNING_ALLOWED=NO
